### PR TITLE
Fixing URLs  and adding an imprint

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by djc** [comment]
LGTM.

**Comment by Kingdutch** [comment]
@badboy Ah I see those policy pages don't actually exist yet. They're stuck in #20 which I believe needed review from/modification by @RafaelaWetzel

**Comment by badboy** [comment]
@Kingdutch I see. Let's get the CoC in though, it's linked from our blog.

**Comment by Kingdutch** [comment]
@badboy My bad apparently the CoC and A11y statement were already put in separately :) The other PR only moved them around a bit. Not sure why it gave me a different diff and local experience just now.

Merging and deploying this :)

**Comment by RafaelaWetzel** [comment]
Quoting @flaki:

> Another related thing I noticed, is that on our info page we refer (and link) to the PyCon attendee/staff reporting procedure. It is not ideal that we link to an external site and we should adopt and create our own policies for this based on the linked pages.

I've adapted the Attendee + Staff Procedure For Reporting Code of Conduct Incidents; will send it over on Zulip @Kingdutch

**Pull request merged**
