### PR TITLE
Add Team Page

### PR DESCRIPTION
**Pull request by Kingdutch**
Here we begin work to set up the website so we can add more pages and start adding team members to the team page.

This is a work in progress.

image

image

image

### CODE REVIEW

**Comment by dutchmartin** [comment]
Cool, I've tested this. I found that if you click on a social link, it first opens the description, and then goes to the link. That seems like a bug to me.

**Comment by Kingdutch** [comment]
Ah you're right, I had fixed this for keyboard but not for mouse apparently 🙈

**Comment by dutchmartin** [comment]
This page looks better with content:
image

**Comment by Kingdutch** [comment]
I fixed the bug that was flagged by @dutchmartin so I think we can merge this : )

We can pick up the colors in a follow-up PR.

**Review by dutchmartin — APPROVED** [review]
Nice. But should we merge this in trunk/develop instead of master?

**Comment by Kingdutch** [comment]
@dutchmartin Not sure if it matters, the website itself runs from the gh-pages branch so merging to master should be fine (if it's not we can always revert 😋 )

**Comment by dutchmartin** [comment]
@Kingdutch I expected that master was auto-deployed to github pages, but this is not the case now.

**Pull request merged**
